# Generated by Django 5.2.6 on 2025-09-08 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafioadl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtarea',
            name='tarea_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarea', to='desafioadl.tarea'),
        ),
    ]
